try {
  window.someNonexistentFunction();
} catch (error){
  console.log("An error happened!");
}
